DB_USERNAME = "avnadmin"
DB_PASSWORD = ""
DB_NAME = ""
DB_HOST = ""
DB_PORT = 25745

SQLALCHEMY_DATABASE_URI = f"postgresql://{DB_USERNAME}:{DB_PASSWORD}@{DB_HOST}:{DB_PORT}/{DB_NAME}"
SQLALCHEMY_TRACK_MODIFICATIONS = False
